<?php
defined('_JEXEC') or exit();

use Joomla\CMS\MVC\Controller\BaseController;

class AgentcalcController extends BaseController {
    public function __construct($config = [], MVCFactoryInterface $factory = null,  $app = null,  $input = null)
    {
        parent::__construct($config, $factory, $app, $input);
    }

    public function display($cachable = false, $urlparams = array())
    {
        return parent::display($cachable, $urlparams); // TODO: Change the autogenerated stub
    }
}